// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// plt_check.cpp
bool plt_check_(std::string path);
extern "C" SEXP _palettizer_plt_check_(SEXP path) {
  BEGIN_CPP11
    return cpp11::as_sexp(plt_check_(cpp11::as_cpp<cpp11::decay_t<std::string>>(path)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_palettizer_plt_check_", (DL_FUNC) &_palettizer_plt_check_, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_palettizer(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
